#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

VIEWER_ENV="${VIEWER_ENV:-dfmviewer}"
CCTBX_ENV="${CCTBX_ENV:-cctbx-env}"
OUT_DIR="$SCRIPT_DIR/generated"
IMAGE_SRC=""
IMAGE_SIZE=256
PORT=8051
MIN_SIGMA="1e-12"
RAW_HKL=""
FCF=""
INTEGRATE_HKL=""
CONFIG_FILE=""
SAVE_CONFIG=""
BUILD_ONLY=0

write_config_file() {
    local config_path="$1"
    mkdir -p "$(dirname "$config_path")"
    {
        echo "# Generated by run_sres_viewer.sh"
        echo "# Re-run with: ./run_sres_viewer.sh --config $config_path"
        printf 'INTEGRATE_HKL=%q\n' "$INTEGRATE_HKL"
        printf 'RAW_HKL=%q\n' "$RAW_HKL"
        printf 'FCF=%q\n' "$FCF"
        printf 'IMAGE_SRC=%q\n' "$IMAGE_SRC"
        printf 'OUT_DIR=%q\n' "$OUT_DIR"
        printf 'IMAGE_SIZE=%q\n' "$IMAGE_SIZE"
        printf 'PORT=%q\n' "$PORT"
        printf 'MIN_SIGMA=%q\n' "$MIN_SIGMA"
        printf 'VIEWER_ENV=%q\n' "$VIEWER_ENV"
        printf 'CCTBX_ENV=%q\n' "$CCTBX_ENV"
    } > "$config_path"
}

usage() {
    cat <<EOF
Usage:
  ./run_sres_viewer.sh --integrate-hkl PATH --raw-hkl PATH --fcf PATH [options]
  ./run_sres_viewer.sh --config PATH [options]

Required:
  --integrate-hkl PATH   XDS INTEGRATE.HKL with observed frame information
  --raw-hkl PATH         SHELX raw HKLF4 .hkl containing Fo^2 and sigma(Fo^2)
  --fcf PATH             SHELX .fcf containing Fc^2

Optional:
  --config PATH          Load all pipeline settings from a saved config file
  --save-config PATH     Save the effective settings to a reusable config file
  --image-src DIR        Source frame directory (.tiff/.tif/.png/.jpg)
  --out-dir DIR          Output directory for CSV, summary, and prepared images
  --image-size N         Longest edge for prepared PNGs (default: 256)
  --port N               Dash port (default: 8051)
  --min-sigma X          Drop rows with scaled sigma <= X (default: 1e-12)
  --build-only           Build CSV/images/config but do not launch the Dash viewer
  --help                 Show this message

Environment overrides:
  VIEWER_ENV             Conda env used for Dash/Pillow tasks (default: dfmviewer)
  CCTBX_ENV              Conda env used for cctbx mapping (default: cctbx-env)
EOF
}

ARGS=("$@")
for ((i=0; i<${#ARGS[@]}; i++)); do
    if [[ "${ARGS[$i]}" == "--config" ]]; then
        if (( i + 1 >= ${#ARGS[@]} )); then
            echo "Missing value after --config" >&2
            exit 2
        fi
        CONFIG_FILE="${ARGS[$((i + 1))]}"
        break
    fi
done

if [[ -n "$CONFIG_FILE" ]]; then
    if [[ ! -f "$CONFIG_FILE" ]]; then
        echo "Config file not found: $CONFIG_FILE" >&2
        exit 2
    fi
    set +u
    source "$CONFIG_FILE"
    set -u
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --integrate-hkl)
            INTEGRATE_HKL="$2"
            shift 2
            ;;
        --raw-hkl)
            RAW_HKL="$2"
            shift 2
            ;;
        --fcf)
            FCF="$2"
            shift 2
            ;;
        --config)
            CONFIG_FILE="$2"
            shift 2
            ;;
        --save-config)
            SAVE_CONFIG="$2"
            shift 2
            ;;
        --image-src)
            IMAGE_SRC="$2"
            shift 2
            ;;
        --out-dir)
            OUT_DIR="$2"
            shift 2
            ;;
        --image-size)
            IMAGE_SIZE="$2"
            shift 2
            ;;
        --port)
            PORT="$2"
            shift 2
            ;;
        --min-sigma)
            MIN_SIGMA="$2"
            shift 2
            ;;
        --build-only)
            BUILD_ONLY=1
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -z "$INTEGRATE_HKL" || -z "$RAW_HKL" || -z "$FCF" ]]; then
    usage >&2
    exit 2
fi

if ! command -v conda &> /dev/null ; then
    echo "Conda not found. Please install Miniconda or Anaconda first." >&2
    exit 1
fi

source "$(conda info --base)/etc/profile.d/conda.sh"

if ! conda env list | grep -q "^${CCTBX_ENV}[[:space:]]"; then
    echo "Conda environment '${CCTBX_ENV}' was not found." >&2
    exit 1
fi

if ! conda env list | grep -q "^${VIEWER_ENV}[[:space:]]"; then
    echo "Creating Conda environment '${VIEWER_ENV}'..."
    conda env create -f environment.yml
fi

mkdir -p "$OUT_DIR"
CSV_PATH="$OUT_DIR/sres_viewer_data.csv"
SUMMARY_PATH="$OUT_DIR/sres_viewer_summary.txt"
IMAGE_DST="$OUT_DIR/images"
AUTO_CONFIG_PATH="$OUT_DIR/sres_pipeline.env"

echo "Building SRES dataset..."
conda activate "$CCTBX_ENV"
python "$SCRIPT_DIR/build_sres_data.py" \
    --raw-hkl "$RAW_HKL" \
    --fcf "$FCF" \
    --integrate-hkl "$INTEGRATE_HKL" \
    --out-csv "$CSV_PATH" \
    --out-summary "$SUMMARY_PATH" \
    --min-sigma "$MIN_SIGMA"

conda activate "$VIEWER_ENV"

if [[ -n "$IMAGE_SRC" ]]; then
    echo "Preparing frame images..."
    python "$SCRIPT_DIR/prepare_frame_images.py" \
        --src-dir "$IMAGE_SRC" \
        --dst-dir "$IMAGE_DST" \
        --max-size "$IMAGE_SIZE"
else
    echo "No --image-src provided. The viewer will still start, but no frame images will be shown."
fi

write_config_file "$AUTO_CONFIG_PATH"
echo "Saved reusable config: $AUTO_CONFIG_PATH"

if [[ -n "$SAVE_CONFIG" ]]; then
    write_config_file "$SAVE_CONFIG"
    echo "Saved reusable config: $SAVE_CONFIG"
fi

if [[ "$BUILD_ONLY" -eq 1 ]]; then
    echo "Build complete."
    echo "To reopen this dataset later, run:"
    echo "  ./run_sres_viewer.sh --config $AUTO_CONFIG_PATH"
    echo "Or open the generated data directly:"
    echo "  ./run_viewer.sh --csv $CSV_PATH --image-dir $IMAGE_DST --y-col SRES"
    exit 0
fi

echo "Starting viewer..."
python "$SCRIPT_DIR/dfm_viewer.py" \
    --csv "$CSV_PATH" \
    --image-dir "$IMAGE_DST" \
    --x-col zobs \
    --y-col SRES \
    --port "$PORT" \
    --title "SRES vs zobs"
